spring:
  application:
    name: mottu

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:{$MYSQL_PORT:3306}/${MYSQL_DATABASE:mottu}
    username: ${MYSQL_USER:mottu}
    password: ${MYSQL_PASS:mottu}
    driver-class-name: com.mysql.cj.jdbc.Driver
